Task2.1
DzianCPP/phpNativeMVC pull request #2
Opened 2022-11-04 09:57 UTC by DzianCPP

2022-11-04 11:11 UTC, steepbeaver commented on index.php
>  <?php
Let's put this file inside the public directory

2022-11-04 11:11 UTC, steepbeaver commented on index.php
> +header('Location: system/app.php');
We don't need to use redirect here. Let's do: `require_once __DIR__ . '/../bootstrap/app.php'`;

In the file bootstrap/app.php:

- include 'base-config.php';
- include 'base-paths.php';
- require_once 'autoload.php';
- init application (new App())

These files allow us to define constants such as:

- Main application constants
- Paths

2022-11-04 11:11 UTC, steepbeaver commented on system/autoload.php
> -    $folder = "/opt/lampp/htdocs/intern/controllers/";
Use constant was defined in base-paths.php (example: __CONTROLLER_PATH)

2022-11-04 11:11 UTC, steepbeaver commented on controllers/AppController.php
> -        $filePath = "/opt/lampp/htdocs/intern/view/mainPage.html";
Use constant was defined in base-paths.php (example: __VIEW_PATH)

2022-11-04 11:11 UTC, steepbeaver commented on controllers/UserController.php
>      private function createUser()
This class should contain only new() and create() methods.

How can I get access to this controller? What URL should I write to go into?

TODO:

- no __construct (right now we don't need that)
- no methods except new() and create()
- should be accessible by URL

2022-11-04 11:11 UTC, steepbeaver commented on controllers/UserController.php
> +$userController = new UserController();
In the current app philosophy, we must avoid code outside classes when we passed through the init steps and already come to controllers

2022-11-04 11:11 UTC, steepbeaver commented on system/autoload.php
> +    $extension = ".php";
Redundant here. But in a common good way.

If you want to keep that - define constant.

2022-11-04 11:23 UTC, steepbeaver reviewed
Folder 'images' should be inside the 'public' folder and be accessible by URL

2022-11-04 11:23 UTC, steepbeaver commented on view/mainPage.html
> +    <link rel="icon" type="image/x-icon" href="../images/favicon.ico">
We don't use a path to file when using static files line icons, images, or any docs. We must use the URL here.

2022-11-04 11:23 UTC, steepbeaver commented on view/mainPage.html
> +    <form class="new-user-form" method="POST" action="../controllers/UserController.php">
We don't use a path to file when we want to send a request. We must use a URL here

2022-11-04 11:26 UTC, steepbeaver commented on controllers/UserController.php
> +        return $newUserData;
Redundant. What is the reason to return data here?

2022-11-04 11:37 UTC, steepbeaver commented on system/autoload.php
>  function myAutoLoad($className)
Good idea to use autoload

2022-11-07 08:15 UTC, nashalda requested changes

2022-11-07 08:15 UTC, nashalda commented on public/index.php
> +
корневая папка твоего веб-сервера - public
![image](https://user-images.githubusercontent.com/15914080/200253605-230e1492-4dde-4fcd-b55d-201995276a78.png)
![image](https://user-images.githubusercontent.com/15914080/200253691-4523984b-c6e7-4a82-98fe-70a7bd4b3f73.png)

2022-11-07 08:15 UTC, nashalda commented on public/index.php
> +require_once "../system/app.php";
favicon.ico переложи сюда в корень public. Потому что это не совсем images и обычно его кладут здесь

2022-11-07 08:15 UTC, nashalda commented on core/controllers/UserController.php
> +            $_REQUEST['email'],
$_REQUEST непонятно зачем заменил. $_POST и $_GET отдельно - это лучшая практика

2022-11-07 08:15 UTC, nashalda commented on core/controllers/UserController.php
> +        return;
он точно здесь нужен?

2022-11-07 08:15 UTC, nashalda commented on public/assets/css/style.css
>      font-size: larger;
font-size дважды

2022-11-07 08:15 UTC, nashalda commented on public/assets/css/style.css
>      text-shadow: 2px 2px 2px rgba(70, 50, 70, 0.9);
при использовании шрифтов, которых может не быть в системе  'Lucida Typewriter Serif' нужно всегда определять дефолтный

2022-11-07 08:15 UTC, nashalda commented on public/assets/css/style.css
>      font-family: 'Lucida Sans';
И тут тоже

2022-11-07 08:15 UTC, nashalda commented on public/assets/css/style.css
> +    padding: 10% 10px 10px 10px;
погугли, допустимо ли смешение % and px, то есть корректно ли так писать
padding: 10% 10px 10px 10px;
потом расскажешь, я сам не уверен корректно или нет)

2022-11-07 08:15 UTC, nashalda commented on view/newUserForm.html
> +    <form class="new-user-form" method="POST" action="/core/controllers/UserController.php">
action="/core/controllers/UserController.php">
мы не должны раскрывать внутреннюю структуру нашего проекта. Всё, что нужно знать посетителю сайта, это адреса статичных ресурсов типа картинки, js, css

2022-11-07 08:15 UTC, nashalda commented on view/newUserForm.html
> +            <option>Active</option>
"Пустые поля должны иметь placeholder. В <option> обязательно используйте атрибут “value”."

2022-11-07 08:15 UTC, nashalda commented on view/newUserForm.html
> +        <select name="gender" id="gender-select-input" class="input-select" id="inputSelectGender">
id

2022-11-07 08:15 UTC, nashalda commented on view/newUserForm.html
> +        <label class="form-label" for="gender-select-input">Gender</label>
for="gender-select-input" - немного избыточное id 
"gender" вполне достаточно

2022-11-07 08:15 UTC, nashalda commented on view/newUserForm.html
> +        <br>
<br> при вёрстке используются очень-очень редко. Используй div блоки

2022-11-07 08:15 UTC, nashalda commented on system/base-paths.php
> +<?php
а где файл base-config.php используется?

2022-11-07 08:56 UTC, DzianCPP commented on system/base-paths.php
> +<?php
removed the file

2022-11-07 08:57 UTC, DzianCPP commented on view/newUserForm.html
> +        <br>
changed all the <br>-tags to <div>-blocks

2022-11-07 08:58 UTC, DzianCPP commented on view/newUserForm.html
> +        <label class="form-label" for="gender-select-input">Gender</label>
refactored

2022-11-07 08:59 UTC, DzianCPP commented on view/newUserForm.html
> +        <select name="gender" id="gender-select-input" class="input-select" id="inputSelectGender">
removed a duplicate

2022-11-07 08:59 UTC, DzianCPP commented on view/newUserForm.html
> +            <option>Active</option>
added value to status input

2022-11-07 08:59 UTC, DzianCPP commented on public/assets/css/style.css
> +    padding: 10% 10px 10px 10px;
done

2022-11-07 08:59 UTC, DzianCPP commented on public/assets/css/style.css
>      font-family: 'Lucida Sans';
done

2022-11-07 09:00 UTC, DzianCPP commented on public/assets/css/style.css
>      text-shadow: 2px 2px 2px rgba(70, 50, 70, 0.9);
done

2022-11-07 09:00 UTC, DzianCPP commented on public/assets/css/style.css
>      font-size: larger;
removed

2022-11-07 09:00 UTC, DzianCPP commented on core/controllers/UserController.php
> +        return;
nope

2022-11-07 09:00 UTC, DzianCPP commented on core/controllers/UserController.php
> +            $_REQUEST['email'],
changed to $_POST back again

2022-11-07 09:01 UTC, DzianCPP commented on index.php
>  <?php
done

2022-11-07 09:02 UTC, DzianCPP commented on index.php
> +header('Location: system/app.php');
refactored it but now working on the Router

2022-11-07 11:52 UTC, DzianCPP commented on controllers/UserController.php
> +        return $newUserData;
removed

2022-11-07 12:25 UTC, nashalda requested changes

2022-11-07 12:25 UTC, nashalda commented on view/mainPage.html
> +<form class="new-user-form" method="POST" action="/view/newUserForm.html">
форма здесь избыточна - обычная <a href

2022-11-07 13:50 UTC, steepbeaver commented on bootstrap/app.php
> +$params = $track->getParams();
Please, run your application and after that manipulate with routes

2022-11-07 13:50 UTC, steepbeaver commented on bootstrap/base-paths.php
> +define('NEW_USER_HTML_PATH', BASE_PATH . '/../view/newUserForm.html');
Don't forget to remove that

2022-11-07 13:50 UTC, steepbeaver commented on bootstrap/routes.php
> +    'user/new' => [
In your current implementation, you can run this route as GET and POST. But let's create new and create routes and restrict access with GET and POST.

2022-11-07 13:50 UTC, steepbeaver commented on bootstrap/routes.php
> +        'action' => 'create'
Do you have a route new with action create?

2022-11-07 13:50 UTC, steepbeaver commented on core/application/Application.php
> +        elseif ($controller === "user" && $action === "create") {
Let's remove if-else construction here and use 'controller' and 'action' elements directly

2022-11-07 13:50 UTC, steepbeaver commented on core/controllers/AppController.php
> +        $file = fopen(MAIN_PAGE, "r");
Let's use VIEW_PATH + string to html

2022-11-07 13:50 UTC, steepbeaver commented on view/newUserForm.html
> +    <form class="new-user-form" method="POST" action="http://localhost/user/new">
We don't use absolute paths in URLs inside our application. This makes development harder and increases the risk of refactoring in case the host changes.

2022-11-08 12:05 UTC, DzianCPP commented on core/application/Application.php
> +        elseif ($controller === "user" && $action === "create") {
done

2022-11-08 12:05 UTC, DzianCPP commented on core/controllers/AppController.php
> +        $file = fopen(MAIN_PAGE, "r");
done

2022-11-08 12:05 UTC, DzianCPP commented on bootstrap/routes.php
> +        'action' => 'create'
changed

2022-11-08 12:06 UTC, DzianCPP commented on bootstrap/routes.php
> +    'user/new' => [
done

2022-11-08 12:07 UTC, DzianCPP commented on bootstrap/base-paths.php
> +define('NEW_USER_HTML_PATH', BASE_PATH . '/../view/newUserForm.html');
done

2022-11-08 12:07 UTC, DzianCPP commented on bootstrap/app.php
> +$params = $track->getParams();
done

2022-11-08 12:07 UTC, DzianCPP commented on view/mainPage.html
> +    <form class="new-user-form" method="POST" action="../controllers/UserController.php">
done

2022-11-08 12:07 UTC, DzianCPP commented on view/mainPage.html
> +    <link rel="icon" type="image/x-icon" href="../images/favicon.ico">
done

2022-11-08 12:08 UTC, DzianCPP commented on controllers/UserController.php
> +$userController = new UserController();
completely changed routing and controller initializing

2022-11-08 12:41 UTC, DzianCPP commented on view/newUserForm.html
> +    <form class="new-user-form" method="POST" action="/core/controllers/UserController.php">
переделал полностью, теперь там роут, которым управлякет роутер

2022-11-08 12:53 UTC, DzianCPP commented on view/mainPage.html
> +<form class="new-user-form" method="POST" action="/view/newUserForm.html">
done

2022-11-16 06:04 UTC, merged