Task2.2
DzianCPP/phpNativeMVC pull request #3
Opened 2022-11-18 08:28 UTC by DzianCPP

2022-11-24 14:53 UTC, nashalda requested changes

2022-11-24 14:53 UTC, nashalda commented on .gitignore
> +/public/images/
а почему не загружаешь /public/images/ ?

2022-11-24 14:53 UTC, nashalda commented on core/application/Database.php
> +    private array $env = [];
особо нет смысла в дефолтном массиве.

2022-11-24 14:53 UTC, nashalda commented on core/application/Database.php
> +        $this->env = $this->getDotEnv();
ты этот  $this->env больше нигде не используешь. поэтому локальной переменной вполне зватит
![image](https://user-images.githubusercontent.com/15914080/203808185-433b2853-a096-49da-b3c5-a4ee8253beb3.png)

2022-11-24 14:53 UTC, nashalda commented on core/application/Database.php
> +<?php
а вообще тебе нужно вынести работу с .ENV в отдельный класс, потому что в нём могут содержаться не только креды к MySQL, но и многие другие

2022-11-24 14:53 UTC, nashalda commented on core/application/Database.php
> +<?php
И внутри этого класса описать исключение, которое будет выбрасываться, если файла .ENV вдруг не существует

2022-11-24 14:53 UTC, nashalda commented on core/application/UsersSeeder.php
> +    public function run(int $count = 10): void
ты нигде не задокументировал, что есть параметр count
 php commands/seedUsers.php -c 22

2022-11-24 14:53 UTC, nashalda commented on core/view/users.php
> +                        <a href='/user/edit?userID={<?php echo $userID;?>}'>Edit</a>
от это не очень

вариант лучше
/user/edit?userID=<?php echo $userID;?>

вариант ещё лучше
/user/edit/<?php echo $userID;?>

и аттрибуты тегов пдинообразно. я предпочитаю, как и большинство разработчиков, в двойных кавычках

2022-11-24 14:53 UTC, nashalda commented on core/view/users.php
> +                           onclick="sendDeleteRequest(this.id)">
в js

2022-11-24 14:55 UTC, DzianCPP commented on .gitignore
> +/public/images/
случайно прописал) этой папки и не существует

2022-11-24 15:00 UTC, DzianCPP commented on core/application/Database.php
> +    private array $env = [];
done

2022-11-24 15:23 UTC, DzianCPP commented on core/application/Database.php
> +<?php
done

2022-11-24 15:29 UTC, DzianCPP commented on core/application/UsersSeeder.php
> +    public function run(int $count = 10): void
прописал в README инструкцию по аргументам

2022-11-25 08:11 UTC, nashalda requested changes

2022-11-25 08:11 UTC, nashalda commented on core/view/404.php
> +        <a href="/public">Back to main page</a>
/public ? )

2022-11-25 08:11 UTC, nashalda commented on core/view/new.php
> +                style="color: red;"></div>
проверь на inline стили и вынеси в css

2022-11-25 08:11 UTC, nashalda commented on core/application/Database.php
> +    private function getDotEnv(): array
этот метод точно используется?

2022-11-25 08:11 UTC, nashalda commented on core/application/Router.php
лучше используй не псевдоним, а array_key_exists в isRouteValid

2022-11-25 08:11 UTC, nashalda commented on core/view/edit.php
> +                  <option value="<?php echo $gender; ?>">
надо добавить selected, потому что у тебя селекты сбрасываются когда переходишь в форму редактирования
https://w3codegenerator.com/article/how-to-display-select-option-of-select-tag-as-selected-using-foreach-method-in-php

после того, как ты это сделаешь станет понятно куда "запихнуть" массив из genders.php и status.php

2022-11-25 09:00 UTC, DzianCPP commented on core/view/404.php
> +        <a href="/public">Back to main page</a>
нет, конечно) Просто /

2022-11-25 09:01 UTC, DzianCPP commented on core/application/Database.php
> +    private function getDotEnv(): array
убрал

2022-11-25 11:34 UTC, DzianCPP commented on core/view/new.php
> +                style="color: red;"></div>
я вообще этот дуолил стиль, он там излишний

2022-11-25 11:42 UTC, DzianCPP commented on core/view/edit.php
> +                  <option value="<?php echo $gender; ?>">
закинул в бутстрап, так как эта инфа пусть лучше подгружается при запуске апплика, мне кажется

2022-11-25 11:46 UTC, DzianCPP commented on core/view/users.php
> +                           onclick="sendDeleteRequest(this.id)">
слишком сложно, закрываю)

2022-11-25 13:39 UTC, merged